[package]
name = "warch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rand = "0.8.5"
sdl2 = "0.35.2"
clap = {version = "4.0.29", features = ["derive"]}